### ISSUE TITLE
broken tlogclient multiple server unit test

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#310] opened 2017-07-07 01:47 UTC
A tlogclient unit test has failed now a couple of times on master code, log:

```
t=2017-07-07T01:42:14+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:33302" module=global caller=redis.go:47
t=2017-07-07T01:42:14+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:40954" module=global caller=redis.go:47
t=2017-07-07T01:42:14+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:45127" module=global caller=redis.go:47
t=2017-07-07T01:42:14+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:33602" module=global caller=redis.go:47
t=2017-07-07T01:42:14+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:37472" module=global caller=redis.go:47
t=2017-07-07T01:42:14+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:42434" module=global caller=redis.go:47
t=2017-07-07T01:42:14+0000 lvl=dbug msg="received handshake request from incoming connection" module=global caller=server.go:157
t=2017-07-07T01:42:14+0000 lvl=dbug msg="incoming connection checks out with version: 1.1.0-alpha" module=global caller=server.go:167
t=2017-07-07T01:42:14+0000 lvl=dbug msg="create vdisk with expectedSequence:0" module=global caller=vdisk_mgr.go:65
t=2017-07-07T01:42:14+0000 lvl=dbug msg="handshake phase successfully completed" module=global caller=server.go:192
t=2017-07-07T01:42:14+0000 lvl=dbug msg="replying handshake with status: OK" module=global caller=server.go:219
t=2017-07-07T01:42:18+0000 lvl=info msg="tlogclient : reconnect from read because of : EOF" module=global caller=client.go:336
FAIL
FAIL	github.com/zero-os/0-Disk/tlog/tlogclient	56.603s
```

**Comment by GlenDC** [comment] 2017-07-07 18:56
The cause of this fail seems to happen most commits I push to GitHub, so it shouldn't be too hard to reproduce this locally hopefully.

**Comment by iwanbk** [comment] 2017-07-10 03:16
is this the same error as https://travis-ci.org/zero-os/0-Disk/jobs/250433968? I can't reproduce it locally

**Comment by GlenDC** [comment] 2017-07-10 03:19
Yup it is. And we better find a way to reproduce it, because it triggers quite easily on Travis. In best case it just means it triggers a false error. But In a more realistic (and worst) case it actually means we have some serious bug hidden in the darkness.

**Comment by chrisvdg** [comment] 2017-07-10 09:28
@iwanbk How do you run the tests?
If I run make test, it fails for me, if I run go test in the tlogclient package itself, the tests pass for me.

**Comment by iwanbk** [comment] 2017-07-10 09:32
> @iwanbk How do you run the tests?

`go test`

`go test -race`

will try the make test

**Comment by iwanbk** [comment] 2017-07-10 09:42
4 `make test`, all of them failed on `gonbdserver` package

```
goroutine 56 [IO wait]:
net.runtime_pollWait(0x7f83b6483f58, 0x72, 0x7)
	/home/ibk/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42001a0d8, 0x72, 0xae8460, 0xae45f8)
	/home/ibk/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42001a0d8, 0xc4225ca080, 0x10)
	/home/ibk/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc42001a070, 0xc4225ca080, 0x10, 0x10, 0x0, 0xae8460, 0xae45f8)
	/home/ibk/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc420190008, 0xc4225ca080, 0x10, 0x10, 0x0, 0x0, 0x0)
	/home/ibk/go/src/net/net.go:181 +0x70
io.ReadAtLeast(0x7f83b6484298, 0xc420190008, 0xc4225ca080, 0x10, 0x10, 0x10, 0xaf0c40, 0x8255e0, 0xc4225ca050)
	/home/ibk/go/src/io/io.go:307 +0xa9
io.ReadFull(0x7f83b6484298, 0xc420190008, 0xc4225ca080, 0x10, 0x10, 0x10, 0x0, 0x0)
	/home/ibk/go/src/io/io.go:325 +0x58
encoding/binary.Read(0x7f83b6484298, 0xc420190008, 0xaede60, 0xb405f8, 0x7c89a0, 0xc4225ca050, 0x0, 0x0)
	/home/ibk/go/src/encoding/binary/binary.go:244 +0x1012
github.com/zero-os/0-Disk/gonbdserver/nbd.(*IntegrityTest).Receiver(0xc4201a40d0)
	/home/ibk/pathgo/src/github.com/zero-os/0-Disk/gonbdserver/nbd/integrity_test.go:275 +0x199
created by github.com/zero-os/0-Disk/gonbdserver/nbd.(*IntegrityTest).Run
	/home/ibk/pathgo/src/github.com/zero-os/0-Disk/gonbdserver/nbd/integrity_test.go:381 +0xd1

goroutine 57 [select]:
github.com/zero-os/0-Disk/gonbdserver/nbd.(*IntegrityTest).Ticker(0xc4201a40d0)
	/home/ibk/pathgo/src/github.com/zero-os/0-Disk/gonbdserver/nbd/integrity_test.go:358 +0x2d7
created by github.com/zero-os/0-Disk/gonbdserver/nbd.(*IntegrityTest).Run
	/home/ibk/pathgo/src/github.com/zero-os/0-Disk/gonbdserver/nbd/integrity_test.go:382 +0xf6
FAIL	github.com/zero-os/0-Disk/gonbdserver/nbd	120.860s
?   	github.com/zero-os/0-Disk/log	[no test files]
?   	github.com/zero-os/0-Disk/nbdserver	[no test files]
ok  	github.com/zero-os/0-Disk/nbdserver/ardb	23.944s
ok  	github.com/zero-os/0-Disk/nbdserver/lba	0.013s
?   	github.com/zero-os/0-Disk/redisstub	[no test files]
ok  	github.com/zero-os/0-Disk/tlog	0.010s
?   	github.com/zero-os/0-Disk/tlog/schema	[no test files]
ok  	github.com/zero-os/0-Disk/tlog/tlogclient	14.821s
?   	github.com/zero-os/0-Disk/tlog/tlogclient/blockbuffer	[no test files]
?   	github.com/zero-os/0-Disk/tlog/tlogclient/decoder	[no test files]
?   	github.com/zero-os/0-Disk/tlog/tlogclient/examples/send_tlog	[no test files]
?   	github.com/zero-os/0-Disk/tlog/tlogclient/examples/walk_history	[no test files]
?   	github.com/zero-os/0-Disk/tlog/tlogclient/player	[no test files]
ok  	github.com/zero-os/0-Disk/tlog/tlogserver	4.419s
?   	github.com/zero-os/0-Disk/tlog/tlogserver/aggmq	[no test files]
ok  	github.com/zero-os/0-Disk/tlog/tlogserver/erasure	0.002s [no tests to run]
ok  	github.com/zero-os/0-Disk/tlog/tlogserver/server	3.360s
?   	github.com/zero-os/0-Disk/tlog/tlogserver/slavesync	[no test files]
?   	github.com/zero-os/0-Disk/zeroctl	[no test files]
?   	github.com/zero-os/0-Disk/zeroctl/cmd	[no test files]
?   	github.com/zero-os/0-Disk/zeroctl/cmd/config	[no test files]
?   	github.com/zero-os/0-Disk/zeroctl/cmd/copyvdisk	[no test files]
?   	github.com/zero-os/0-Disk/zeroctl/cmd/delvdisk	[no test files]
?   	github.com/zero-os/0-Disk/zeroctl/cmd/list	[no test files]
ok  	github.com/zero-os/0-Disk/zeroctl/cmd/restore	0.133s
Makefile:44: recipe for target 'testgo' failed
make: *** [testgo] Error 1
```

@chrisvdg how is your output?

**Comment by chrisvdg** [comment] 2017-07-10 09:50
@iwanbk, mine failed on tlogclient as the previously mentioned error

`
t=2017-07-10T11:44:56+0200 lvl=info msg="tlogclient : reconnect from read because of : EOF" module=global caller=client.go:336
FAIL
FAIL    github.com/zero-os/0-Disk/tlog/tlogclient       37.070s
?       github.com/zero-os/0-Disk/tlog/tlogclient/blockbuffer   [no test files]
?       github.com/zero-os/0-Disk/tlog/tlogclient/decoder       [no test files]
?       github.com/zero-os/0-Disk/tlog/tlogclient/examples/send_tlog    [no test files]
?       github.com/zero-os/0-Disk/tlog/tlogclient/examples/walk_history [no test files]
?       github.com/zero-os/0-Disk/tlog/tlogclient/player        [no test files]
ok      github.com/zero-os/0-Disk/tlog/tlogserver       4.480s
?       github.com/zero-os/0-Disk/tlog/tlogserver/aggmq [no test files]
ok      github.com/zero-os/0-Disk/tlog/tlogserver/erasure       0.002s [no tests to run]
ok      github.com/zero-os/0-Disk/tlog/tlogserver/server        3.564s
?       github.com/zero-os/0-Disk/tlog/tlogserver/slavesync     [no test files]
?       github.com/zero-os/0-Disk/zeroctl       [no test files]
?       github.com/zero-os/0-Disk/zeroctl/cmd   [no test files]
?       github.com/zero-os/0-Disk/zeroctl/cmd/config    [no test files]
?       github.com/zero-os/0-Disk/zeroctl/cmd/copyvdisk [no test files]
?       github.com/zero-os/0-Disk/zeroctl/cmd/delvdisk  [no test files]
?       github.com/zero-os/0-Disk/zeroctl/cmd/list      [no test files]
ok      github.com/zero-os/0-Disk/zeroctl/cmd/restore   0.164s
Makefile:44: recipe for target 'testgo' failed
make: *** [testgo] Error 1
`

gonbdserver did not fail for me
`
ok      github.com/zero-os/0-Disk/gonbdserver/nbd       15.904s
`   

I did find this now, scrolling though the output  
`
--- FAIL: TestMultipleServerBasicMasterFailToFlush (25.19s)
        multiple_server_test.go:144: Create tlog servers
        multiple_server_test.go:153: connect client
        multiple_server_test.go:165: write data to server #1
        multiple_server_test.go:194: write data to server #2
        common_test.go:27: testClientWaitSeqFlushed timeout
`

**Comment by chrisvdg** [comment] 2017-07-10 10:56
> is this the same error as https://travis-ci.org/zero-os/0-Disk/jobs/250433968?

Scrolling through the travis logs :

```
t=2017-07-05T16:53:19+0000 lvl=info msg="flush of vdiskID=myimg failed: [error during flush idx 0: redis Send failed: no connectionPool exists for index 0 error during flush idx 1: redis Send failed: no connectionPool exists for index 1]" module=global caller=flusher.go:173

t=2017-07-05T16:53:19+0000 lvl=info msg="flush myimg failed: flush vdiskID=myimg failed" module=global caller=vdisk.go:411

--- FAIL: TestMultipleServerResendHotReload (20.11s)
	multiple_server_test.go:144: Create tlog servers
	multiple_server_test.go:153: connect client
	multiple_server_test.go:165: write data to server #1
	multiple_server_test.go:194: write data to server #2
	common_test.go:27: testClientWaitSeqFlushed timeout
```

Seems to be related to when redis is flushed?

**Comment by iwanbk** [comment] 2017-07-10 11:04
> Seems to be related to when redis is flushed?

No, the error is intended (by closing the redis pool), to simulate scenario where tlog server failed to flush.
If current server failed to flush, tlog client should move to another server.

I have a fix in `fix-tlog-test-multipleserver`. 
In this fix, tlogclient **always** move to another server when error happens.

It previously sometimes try to reconnect to current server.

@chrisvdg would be great if you can try my fix. It passed travis twice.

**Comment by chrisvdg** [comment] 2017-07-10 11:12
It is still failing for me
```
FAIL    github.com/zero-os/0-Disk/tlog/tlogclient       79.919s
?       github.com/zero-os/0-Disk/tlog/tlogclient/blockbuffer   [no test files]
?       github.com/zero-os/0-Disk/tlog/tlogclient/decoder       [no test files]
?       github.com/zero-os/0-Disk/tlog/tlogclient/examples/send_tlog    [no test files]
?       github.com/zero-os/0-Disk/tlog/tlogclient/examples/walk_history [no test files]
?       github.com/zero-os/0-Disk/tlog/tlogclient/player        [no test files]
ok      github.com/zero-os/0-Disk/tlog/tlogserver       4.429s
?       github.com/zero-os/0-Disk/tlog/tlogserver/aggmq [no test files]
ok      github.com/zero-os/0-Disk/tlog/tlogserver/erasure       0.005s [no tests to run]
ok      github.com/zero-os/0-Disk/tlog/tlogserver/server        3.535s
?       github.com/zero-os/0-Disk/tlog/tlogserver/slavesync     [no test files]
?       github.com/zero-os/0-Disk/zeroctl       [no test files]
?       github.com/zero-os/0-Disk/zeroctl/cmd   [no test files]
?       github.com/zero-os/0-Disk/zeroctl/cmd/config    [no test files]
?       github.com/zero-os/0-Disk/zeroctl/cmd/copyvdisk [no test files]
?       github.com/zero-os/0-Disk/zeroctl/cmd/delvdisk  [no test files]
?       github.com/zero-os/0-Disk/zeroctl/cmd/list      [no test files]
ok      github.com/zero-os/0-Disk/zeroctl/cmd/restore   0.162s
Makefile:44: recipe for target 'testgo' failed
make: *** [testgo] Error 1
```

Same fail message as well:
```
--- FAIL: TestMultipleServerBasicMasterFailToFlush (68.07s)
        multiple_server_test.go:144: Create tlog servers
        multiple_server_test.go:153: connect client
        multiple_server_test.go:165: write data to server #1
        multiple_server_test.go:194: write data to server #2
        common_test.go:27: testClientWaitSeqFlushed timeout
```

**Comment by iwanbk** [comment] 2017-07-17 06:48
Because my Mac charger got burnt (yeah, i saw the sparks), i use a smallest VM (512MB of RAM) from digital ocean.
It still can't reproduce the issue using both make testgo and make testrace

On the other hand, around 10% of travis build failed for this test for me.

**Comment by iwanbk** [comment] 2017-07-17 10:04
i finally able to reproduce it using old PC from 2009/2010 :dancer:

**Comment by iwanbk** [comment] 2017-07-17 10:15
```
i finally able to reproduce it using old PC from 2009/2010 :dancer:
```
spoke too soon, the erasure encoder failed for this PC. So it basically failed for all the tests

**Comment by iwanbk** [comment] 2017-07-19 04:02
I finally able to reproduce this issue on my fast PC.
I created virtualbox VM using vagrant and cap the CPU to 80%.

**Comment by iwanbk** [comment] 2017-07-19 04:19
I think i found the real issue.

There are blocks that already flushed but for some reason client still try to resend it (lets say it block X)
This is not a problem in single server but causing issue on multiple servers.
Because when connecting to 2nd server, client set the expected first sequence to X, and because X+1, X+2, etc... already marked to be sent, it never resend to 2nd server

**Closed** 2017-07-19 09:10 UTC
Labels: priority_major, state_inprogress, type_bug
