### ISSUE TITLE
broken tlog/tlogserver/server test

### ISSUE THREAD

**Issue by chrisvdg** [zero-os/0-Disk#349] opened 2017-07-24 12:05 UTC
make testcgo fails from time to time locally(adds-etcdconfig and master branch) and on Travis (adds-etcdconfig branch so far?) for github.com/zero-os/0-Disk/tlog/tlogserver/server

output is a bit lengthy so linking the raw output file: https://pastebin.com/GiaJ8zfw

the test errors out with (line 1007):
`panic: test timed out after 5m0s`

**Comment by iwanbk** [comment] 2017-07-24 13:09
duplicate of #275

**Closed** 2017-07-24 13:16 UTC
Labels: process_duplicate, type_bug, wontfix
