### ISSUE TITLE
delete/dereference tlog (0-stor) meta(data) during `delete vdisk` command

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#468] opened 2017-09-13 03:42 UTC
Currently no tlog meta(data) stored in the 0-Stor cluster for an active-configured tlog-supported vdisk which is being deleted using the `zeroctl delete vdisk` command.

+ I think there is unique metadata used for each vdisk, which we can just delete;
+ The data itself however might be shared and thus would probably just have to be dereferenced using the API discussed in https://github.com/zero-os/0-stor/issues/197;

**Comment by iwanbk** [comment] 2017-09-18 03:17
i think it is duplicate of #281

**Closed** 2017-09-18 05:02 UTC
Labels: process_duplicate, type_bug, type_feature
